### ISSUE TITLE
Error when exporting from Unity 2017.1.0.f3

### ISSUE THREAD

**Issue by HeadClot** [JamesMcCrae/janusvr_utils#13]
The error is -> DllNotFoundException: UnityFBXExporter

This happens when I hit the Full export button.

It exports the textures but not the meshes.

Unity version: 2017.1.0.f3 
Janus Unity Exporter version: 2.14

**Comment by HeadClot** [comment]
Unity Export to Janus VR works again in 2017.3.0f3

Janus Unity Exporter Version 2.14

**Comment by JamesMcCrae** [comment]
Great!

*James McCrae, PhD*
CEO and Co-Founder
Janus VR Inc.,
Web <http://janusvr.com/> *I* Twitter <https://twitter.com/officialjanusvr>
*I* Reddit <https://www.reddit.com/r/janusVR/> *I *Discord
<https://discord.gg/7eyK2wE> *I *Facebook
<https://www.facebook.com/janusvr/>

On Sat, Dec 30, 2017 at 12:05 AM, Benjamin Stanley <notifications@github.com
