### ISSUE TITLE
Please update the Unreal Engine 4 Exporter

### ISSUE THREAD

**Issue by HeadClot** [JamesMcCrae/janusvr_utils#8]
Not sure what level of priority this is but - Please update the UE4 exporter for Janus. Preferably to version 4.16. According to this git hub it was last updated 10 months ago.

Thank you,
HeadClot

**Comment by distrohelena** [comment]
The Unreal Exporter just got on the priority list, soon it`ll be up to date.

**Comment by HeadClot** [comment]
Thanks @lucasassislar :)

**Comment by marcusg101** [comment]
Hi Im trying to use the plugin but its compiled to 4.16 and 4.17.1 wont load it. are you planning an update soon?

**Comment by HeadClot** [comment]
Giving this a bump as well. With the release of 4.18 and its volumetric lightmap feature it may be worth updating.
